services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/portfolio/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=portfolio_dev
  portfolio-web:
    image: portfolio
    env_file:
      - .env
    command: ["/app/bin/server", "eval", "'MyApp.Release.migrate()'"]
    ports:
      - 8080:8080
