services:
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn --workers 3 --bind 0.0.0.0:8000 config.wsgi:application"
