spring.config.import=optional:file:.env[.properties]
spring.application.name=portfolio

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}


spring.sql.init.mode=always
spring.datasource.initialize=true
spring.sql.init.continue-on-error=true
spring.jpa.generate-ddl=true

springdoc.override-with-generic-response=false

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor=TRACE

custom.content.gist.about-me-url=${GIST_ABOUT_ME_URL}

custom.security.jwt.expiration-in-minutes=${JWT_EXPIRATION_IN_MINUTES}
custom.security.jwt.secret-key=${JWT_SECRET_KEY}

custom.admin.email=${ADMIN_EMAIL}
custom.admin.password=${ADMIN_PASSWORD}