# Generated by Django 5.2.5 on 2025-09-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='TODO'),
        ),
    ]
