# Generated by Django 5.2.5 on 2025-09-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('github_link', models.URLField(max_length=255)),
                ('linkedin_link', models.URLField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
