# Generated by Django 5.2.5 on 2025-09-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_siteinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name_plural': 'Site info'},
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
