# Generated by Django 5.2.5 on 2025-09-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_siteinfo_options_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='display_first',
            field=models.BooleanField(default=False),
        ),
    ]
