name: Deploy Site
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - portfolio_frontend/**
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./portfolio_frontend
        run: npm ci

      - name: Build Vite app
        working-directory: ./portfolio_frontend
        env:
          VITE_API_HOST: ${{secrets.API_HOST}}:w
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        working-directory: ./portfolio_frontend
        run: |
          aws s3 sync dist/ s3://${{secrets.PORTFOLIO_BUCKET_NAME}} \
            --delete \
            --exact-timestamps \